menu:
    Blog: /
    Archive: /archives/
    Twitter: http://twitter.com/rbpinheiro
    GitHub: https://github.com/rbpinheiro
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png
logo_big: /logo.png

# Comment
# e.g disqus: seansun
disqus: blog-pq9sn2ksel
duoshuo:
cloudTie:

# Analytics
# google-analytics:
ga: UA-104159899-1

description: "Rafael Pinheiro's blog: Javascript and shenanigans"
